source 'http://rubygems.org'

gem 'mysql2',             '~>0.2' # 0.2 series compatible with rails 3.0.x series (upgrade to 0.3.x when rails -> 3.1++)
gem 'rails',              '~>3.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

gem "authlogic"
gem 'cancan'
gem 'carrierwave'
gem "hoptoad_notifier"
gem "jammit"
gem 'kaminari'
gem "newrelic_rpm"
gem 'role_model'
gem 'simple_form'

group :development do
  gem 'bones', :path => 'vendor/gems/bones'
  gem "engineyard"
  gem 'ruby-debug19'
  gem "simplecov", :require => false
  gem 'metric_fu'
  gem 'jslint_on_rails'
end

group :test do
  # Capybara is for integration testing
  # FIRST INSTALL THIS http://get.qt.nokia.com/qt/source/qt-mac-opensource-4.7.3.dmg
  # 
  # https://github.com/jnicklas/capybara
  # http://techiferous.com/2010/04/using-capybara-in-rails-3/
  # http://opinionated-programmer.com/2011/02/capybara-and-selenium-with-rspec-and-rails-3/
  # http://blog.plataformatec.com.br/tag/capybara/
  # https://github.com/thoughtbot/capybara-webkit
  # https://github.com/thoughtbot/capybara-webkit/issues/95
  gem 'capybara'
  gem 'capybara-webkit'
  
  # Jasmine is for Javascript testing annd here are some links for how to use it.
  # 
  # http://asciicasts.com/episodes/261-testing-javascript-with-jasmine
  # http://pivotal.github.com/jasmine/
  # http://johnbintz.github.com/jasmine-headless-webkit/
  # http://testdrivenwebsites.com/2010/07/29/html-fixtures-in-jasmine-using-jasmine-jquery/
  # https://github.com/velesin/jasmine-jquery
  # http://relishapp.com/rspec/rspec-rails/v/2-6/file/gettingstarted
  gem 'jasmine'
  gem "jasmine-headless-webkit"

  # And the usual suspects.
  gem 'factory_girl_rails', "~> 1.1.rc1"
  gem 'faker'
  gem 'rr'
  gem "shoulda-matchers",   "~> 1.0.0.beta3"
  gem 'syntax'
end

gem 'ruby-debug19', :group => [:development, :test, :beta]

# And giving good old rspec a second chance
# http://relishapp.com/rspec/rspec-rails/v/2-6/file/gettingstarted
gem 'rspec-rails', :group => [:development, :test]